apiVersion: v1alpha1
kind: Setting
metadata:
  name: meilisearch-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: host
          name: host
          validation: required
          value: 'http://meilisearch:7700'
        - $formkit: text
          label: masterKey
          name: masterKey
          validation: required
          value: '95d031f029c0f93289791d39f01a7f42a2211973'
        - $formkit: text
          label: 搜索结果长度
          name: cropLength
          validation: required|Number
          value: '80'
        - $formkit: checkbox
          name: searchUnpublished
          label: 搜索未发布
          help: 能够搜索非发布状态的文档
          value: false
        - $formkit: checkbox
          name: searchUnexposed
          label: 搜索私有文档
          help: 能够搜索非公开的文档
          value: false
        - $formkit: checkbox
          name: searchRecycled
          label: 搜索已回收
          help: 能够搜索回收站中的文档
          value: false